### ISSUE TITLE
Cant run Docker image 

### ISSUE THREAD

**Issue by rizkydarmadi** [krakendio/krakend-ce#516]
I created file in
etc/krakend.json 

``` {
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "name": "KrakenD - API Gateway",
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "endpoints": [
    {
      "endpoint": "/v1/test-covid-ya",
      "method": "GET",
      "output_encoding": "json",
      "backend": [
        {
          "encoding": "json",
          "sd": "static",
          "method": "GET",
          "host": [
            "https://covid19.mathdro.id/api"
          ],
          "disable_host_sanitize": false
        }
      ]
    }
  ]
} 
```
when I run docker image with :

 ``` sudo docker run -p 8080:8080 -v $PWD:/etc/krakend/ devopsfaith/krakend ```

see the error like this:

```
panic: invalid host

goroutine 1 [running]:
github.com/luraproject/lura/v2/config.URI.CleanHost(0x11, {0xc000157c60, 0x0})
	/go/pkg/mod/github.com/luraproject/lura/v2@v2.0.5/config/uri.go:44 +0xf1
github.com/luraproject/lura/v2/config.URI.CleanHosts(0x0, {0xc0001243c0, 0x1, 0xc000abf4c8})
	/go/pkg/mod/github.com/luraproject/lura/v2@v2.0.5/config/uri.go:35 +0x9f
github.com/luraproject/lura/v2/config.(*ServiceConfig).initBackendDefaults(0xc00079d5a8, 0xc000055e30, 0xc00012e880)
	/go/pkg/mod/github.com/luraproject/lura/v2@v2.0.5/config/config.go:507 +0xad
github.com/luraproject/lura/v2/config.(*ServiceConfig).initEndpoints(0xc000625e00)
	/go/pkg/mod/github.com/luraproject/lura/v2@v2.0.5/config/config.go:437 +0x505
github.com/luraproject/lura/v2/config.(*ServiceConfig).Init(0xc000625e00)
	/go/pkg/mod/github.com/luraproject/lura/v2@v2.0.5/config/config.go:349 +0xb9
github.com/krakendio/krakend-viper/v2.Parser.Parse({_}, {_, _})
	/go/pkg/mod/github.com/krakendio/krakend-viper/v2@v2.0.1/parser.go:37 +0x11d
github.com/krakendio/krakend-cobra/v2.runFunc(0x447f6c0, {0x2b5a539, 0x2, 0x2})
	/go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.0.3/run.go:14 +0x82
github.com/spf13/cobra.(*Command).execute(0x447f6c0, {0xc000754c40, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x447f180)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/krakendio/krakend-cobra/v2.Root.Execute({{0x447f180, {0x0, 0x0, 0x0}, 0xc0006ef090}, {0xc00050c800, 0x3, 0x3}, 0xc0006ef200}, {0x329a160, ...}, ...)
	/go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.0.3/cmd.go:129 +0xaf
github.com/krakendio/krakend-cobra/v2.ExecuteRoot({0x329a160, 0xc0009fd200}, 0x26, {{0x447f180, {0x0, 0x0, 0x0}, 0xc0006ef090}, {0xc00050c800, 0x3, ...}, ...})
	/go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.0.3/cmd.go:26 +0xa5
github.com/krakendio/krakend-cobra/v2.Execute(...)
	/go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.0.3/cmd.go:21
main.main()
	/app/cmd/krakend-ce/main.go:60 +0x61d

```
Can anybody help me, Im so appreciate it

**Comment by taik0** [comment]
Hi @rizkydarmadi 

the host `https://covid19.mathdro.id/api` should be `https://covid19.mathdro.id`

**Comment by jcirionotero** [comment]
"url_pattern": "/api",
"host": [
    "https://covid19.mathdro.id"
]
