### ISSUE TITLE
RabbitMQ backend fails without specifying disable_host_sanitize: true

### ISSUE THREAD

**Issue by tfluehmann** [krakendio/krakend-ce#519]
**Environment info:**

* KrakenD version: 2.0.5
* Backend technology: Rabbitmq 3.10

**Describe the bug**
As already mentioned in https://github.com/krakendio/krakend-ce/issues/255 the rabbitmq plugin has some problem with the rabbitmq host. Once I specify the full rabbitmq URI with the correct protocol suffix I get an error invalid host. Once I remove amqp:// from the host specification krakend starts correctly but suffixes my host with http and suggests to use amqp or amqps which is obviously correct.

It looks like the check in this plugin should not use the following function:
https://github.com/luraproject/lura/blob/v2.0.5/config/uri.go#L41
Or the function does not work properly as expected.

The workaround with `disable_host_sanitize: true`  works for me but it's not the way it should be.

```json
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "name": "Krakend",
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "endpoints": [
    {
      "endpoint": "/v1/my-endpoint",
      "method": "POST",
      "output_encoding": "json",
      "backend": [
        {
          "url_pattern": "/",
          "encoding": "json",
          "sd": "static",
          "method": "GET",
          "extra_config": {
            "backend/amqp/producer": {
              "exchange": "my-exchange",
              "durable": true,
              "delete": false,
              "exclusive": false,
              "no_wait": true,
              "mandatory": false,
              "routing_key": "#",
              "immediate": false,
              "name": "queue"
            }
          },
          "host": [
            "privatequeue:5672/"
          ],
          "disable_host_sanitize": false
        }
      ]
    },
  ]
}

```

**Commands used**
```
docker run --rm -it -v $PWD:/etc/krakend \
        devopsfaith/krakend \
        run -c /etc/krakend/krakend.json -d
```
**Expected behavior**
I expect krakend to connect correctly to my rabbitmq instance which I specified correctly with the protocol in the host without specifying `disable_host_sanitize: true`.

I am happy to create a PR for this issue. but I am not sure what makes sense, extending the cleanHost function in lura, or creating an own one for the amqp(s) case?

**Logs**
Logs without giving the protocol, `disable_host_sanitize: false`:
```
2022/07/04 12:31:26 KRAKEND ERROR: [SERVICE: Logging] Unable to create the logger: getting the extra config for the krakend-gologging module
2022/07/04 12:31:26 KRAKEND DEBUG: [SERVICE: Gin] Debug enabled
2022/07/04 12:31:26 KRAKEND INFO: Starting the KrakenD instance
2022/07/04 12:31:26 KRAKEND ERROR: [BACKEND: /][AMQP] Error getting the channel for http://privatequeue:5672/my-queue: AMQP scheme must be either 'amqp://' or 'amqps://'
2022/07/04 12:31:26 KRAKEND INFO: [SERVICE: Gin] Listening on port: 8080
```
Logs when specifying the protocol and `disable_host_sanitize: false`
```
2022/07/04 15:57:57 Signal intercepted: terminated
2022/07/04 15:57:57 KRAKEND INFO: [SERVICE: Gin] Router execution ended
panic: invalid host

goroutine 1 [running]:
github.com/luraproject/lura/v2/config.URI.CleanHost(0x1e, {0xc00077a7b0, 0x0})
	/go/pkg/mod/github.com/luraproject/lura/v2@v2.0.5/config/uri.go:44 +0xf1
github.com/luraproject/lura/v2/config.URI.CleanHosts(0x0, {0xc00088ce40, 0x1, 0xc000c3f4c8})
	/go/pkg/mod/github.com/luraproject/lura/v2@v2.0.5/config/uri.go:35 +0x9f
github.com/luraproject/lura/v2/config.(*ServiceConfig).initBackendDefaults(0xc00071d148, 0xc0008bc720, 0x273c040)
	/go/pkg/mod/github.com/luraproject/lura/v2@v2.0.5/config/config.go:507 +0xad
github.com/luraproject/lura/v2/config.(*ServiceConfig).initEndpoints(0xc00075e000)
	/go/pkg/mod/github.com/luraproject/lura/v2@v2.0.5/config/config.go:437 +0x505
github.com/luraproject/lura/v2/config.(*ServiceConfig).Init(0xc00075e000)
	/go/pkg/mod/github.com/luraproject/lura/v2@v2.0.5/config/config.go:349 +0xb9
github.com/krakendio/krakend-viper/v2.Parser.Parse({_}, {_, _})
	/go/pkg/mod/github.com/krakendio/krakend-viper/v2@v2.0.1/parser.go:37 +0x11d
github.com/krakendio/krakend-cobra/v2.runFunc(0x447f6c0, {0x2b5a539, 0x3, 0x3})
	/go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.0.3/run.go:14 +0x82
github.com/spf13/cobra.(*Command).execute(0x447f6c0, {0xc0008aa5a0, 0x3, 0x3})
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x447f180)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/krakendio/krakend-cobra/v2.Root.Execute({{0x447f180, {0x0, 0x0, 0x0}, 0xc0005e5ab0}, {0xc0004b6c80, 0x3, 0x3}, 0xc0005e5af0}, {0x329a160, ...}, ...)
	/go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.0.3/cmd.go:129 +0xaf
github.com/krakendio/krakend-cobra/v2.ExecuteRoot({0x329a160, 0xc0008ae360}, 0x26, {{0x447f180, {0x0, 0x0, 0x0}, 0xc0005e5ab0}, {0xc0004b6c80, 0x3, ...}, ...})
	/go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.0.3/cmd.go:26 +0xa5
github.com/krakendio/krakend-cobra/v2.Execute(...)
	/go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.0.3/cmd.go:21
main.main()
	/app/cmd/krakend-ce/main.go:60 +0x61d
```

**Comment by kpacha** [comment]
The flag is enabled in the examples at the documentation: https://www.krakend.io/docs/backends/amqp-producer/
